---
- name: Restart remnawave
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_install_dir }}"
    state: restarted
    services:
      - remnawave

- name: Restart remnanode
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_node_dir }}"
    state: restarted

- name: Restart remnawave-subscription-page
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_subscription_page_dir }}"
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
